let a = 10;
console.log(a);
console.log(typeof a);
a = '' + a; // String(a);
console.log(a);
console.log(typeof a);
a = '42';
console.log(a);
console.log(typeof a);
a = +a; // Number(a);
console.log(a);
console.log(typeof a);
let res = true + false / 5 - null;
console.log(res);
res = (true + false) / '5' - null;
console.log(res);
res = ('5' + +false) / true - null;
console.log(res);
a = 0;
console.log(a);
console.log(typeof a)
a = !!a; // Boolean(a);
console.log(a);
console.log(typeof a);